# Generated by Django 3.0.3 on 2021-08-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20210731_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtaker',
            name='date_finished',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
